CREATE DATABASE TIKTOK_SHOP;
USE TIKTOK_SHOP;

CREATE TABLE USERS (
    userID INT PRIMARY KEY AUTO_INCREMENT,
    fullName VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE WALLETS (
    walletID INT PRIMARY KEY AUTO_INCREMENT,          
    userID INT NOT NULL UNIQUE,                       
    balance DECIMAL(15,2) NOT NULL DEFAULT 0 CHECK (balance >= 0),      
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES USERS(userID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE TRANSACTIONS (
    transactionID INT PRIMARY KEY AUTO_INCREMENT,     
    walletID INT NOT NULL,                            
    type VARCHAR(20) NOT NULL CHECK (type IN ('DEPOSIT', 'WITHDRAW', 'PAYMENT')),                       
    amount DECIMAL(15,2) NOT NULL CHECK (amount > 0),                 
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED')),
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (walletID) REFERENCES WALLETS(walletID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);